# Generated by Django 3.1 on 2020-11-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201102_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamegenres',
            name='gameinfo',
        ),
    ]
