# Generated by Django 3.1 on 2020-11-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_gamegenres_gameinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfos',
            name='game_genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='related_info_genres', to='games.gamegenres'),
            preserve_default=False,
        ),
    ]
